<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<PackageId>Arshid.Aspire.ApiDocs.Extensions</PackageId>
		<Version>1.0.2</Version>
		<Authors>Arash Zandi</Authors>
		<Company>Arshid</Company>
		<Description>An extension to add Swagger, OpenApi, Scalar, CustomUrl and CustomRoute to .Net Aspire.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://github.com/ZandiArash/Arshid-Aspire-ApiDocs-Extensions</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ZandiArash/Arshid-Aspire-ApiDocs-Extensions.git</RepositoryUrl>
		<PackageTags>.Net, Aspire, Scalar, Swagger, OpenAPI</PackageTags>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<!--<PackageOutputPath>$(MSBuildProjectDirectory)\nupkg</PackageOutputPath>-->
		<Title>Aspire ApiDocs Extensions From Arshid</Title>
		<Copyright>MIT</Copyright>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>

	<PropertyGroup>
		<IsPackable>true</IsPackable>
	</PropertyGroup>
	
	<ItemGroup>
	  <None Include="..\icon.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
	</ItemGroup>

</Project>